---

- hosts: localhost
  gather_facts: false
  tasks:
    - name: Setup git with work and personal profiles
      template:
        src: "{{ item }}"
        dest: ~/.{{ item | basename | regex_replace('\.j2','') }}
        backup: yes
      with_fileglob: 
        - ../templates/*.j2

    - name: Add git aliases
      command: echo "foo" > /etc/environment
