- hosts: endpoints
  tasks:

    - name: upload ecocash endpoint artifact
      copy:
        src: /home/jdube/data/ewz/java/epay/epay-ecocash-endpoint/target/epay-ecocash-endpoint-1.0.0.RELEASE.jar
        dest: /data/apps/services/epay-ecocash-endpoint-1.0.0.RELEASE.jar
      become: true

    - name: create service file
      template:
        src: ../templates/epay-ecocash-endpoint.service.j2
        dest: /etc/systemd/system/epay-ecocash-endpoint.service
      become: true

    - name: open firewall ports
      firewalld:
        port: 8080/tcp
        permanent: yes
        state: enabled
      become: true

    - name: reload firewall
      command: firewall-cmd --reload
      become: true

    - name: reload systemd
      become: true
      command: systemctl daemon-reload

    - name: enable and start endpoint service
      systemd:
        name: epay-ecocash-endpoint
        state: started
        enabled: yes
      become: true

