---
- name: Remove old unsupported docker
  yum:
    name:
      - docker
      - docker-client
      - docker-client-latest
      - docker-common 
      - docker-latest 
      - docker-latest-logrotate 
      - docker-logrotate 
      - docker-engine
    state: absent

- name: Install dependencies
  yum:
    name:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
    state: present

- name: Add Docker repo
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docer-ce.repo
  become: yes

- name: install docker
  yum:
    name:
      - docker-ce-18.06.2.ce
    state: present

- name: create docker directory
  file:
    path: /etc/docker
    state: directory
  become: true

- name: copy docker config
  template:
    src: ../templates/daemon.json.j2
    dest: /etc/docker/daemon.json

- name: Start Docker service
  service: 
    name: docker
    state: started
    enabled: yes
    daemon_reload: yes
  become: yes