---
- hosts: scape-master.lo  
  tasks:
  - name: add kubernetes repository
    copy:
      src: ../repos/kubernetes.repo
      dest: /etc/yum.repos.d/kubernetes.repo
      remote_src: no
      
  # install kubernetes
  - name: install kubernetes
    package:
      name: kubelet,kubeadm,kubectl
      state: latest
    become: yes